### PR TITLE
Viewport: Store viewport, rotation in globals

### PR DESCRIPTION
**Pull request by shilman**
Closes N/A

## What I did

Instead of storing the viewport & rotation in addon state, store them in globals.

This has two benefits:
1. users can now set the viewport via globals URL parameters:
	a. `viewport` controls device settings
    b. `viewportRotated` controls device orientation
2. gets us a step closer to using globals across our toolbar addons

## How to test

1. Fire up a sandbox
2. Adjust the viewports in `Page` stories & note URL changes
4. Navigate between stories
5. Navigate to the `viewport` stories in the sandbox and do the same

### CODE REVIEW

**Review by yannbf — COMMENTED** [review]
This looks really good! I think there's a bug with the `viewportRotated` global though.

if you navigate to:
https://62f0fd349c07f78d10b7c017-fetfklaray.chromatic.com/?path=/story/example-button--primary&globals=viewport:mobile1;viewportRotated:!true

it will remove the rotated global and leave the url like so, not loading the viewport in landscape mode:
https://62f0fd349c07f78d10b7c017-fetfklaray.chromatic.com/?path=/story/example-button--primary&globals=viewport:mobile1

**Comment by thafryer** [comment]
@shilman Anything that we can do to help get this merged?

**Comment by shilman** [comment]
closing in favor of https://github.com/storybookjs/storybook/pull/25321

**Comment by shilman** [comment]
@yannbf i suspect that's https://github.com/storybookjs/storybook/issues/25035

**Pull request closed without merging**
