### PR TITLE
Fix: Cannot read properties of undefined (reading 'constantViolations')

### PR DESCRIPTION
**Pull request by ndelangen**
@shilman

### CODE REVIEW

**Comment by ndelangen** [comment]
related: https://github.com/babel/babel/issues/13907

**Comment by ndelangen** [comment]
related: https://github.com/babel/babel/issues/15300

**Comment by ndelangen** [comment]
I've attempted to upgrade to babel-loader 9, this resulted in no changed behaviour (the error still happens)

**Comment by ndelangen** [comment]
Looks like resolution of the bug is happening soon: https://github.com/babel/babel/pull/15301

**Comment by rhenanteix** [comment]
Was solved?? I'm still having this problem in my storybook

**Comment by nishadthajudeen001** [comment]
./node_modules/@angular/cdk/fesm2015/table.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=230&linesState=230)  TypeError: /app/node_modules/@angular/cdk/fesm2015/table.mjs: Cannot set property 'kind' of undefined
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=231&linesState=231)      at transformBlockScopedVariable (/app/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:122:41)
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=232&linesState=232)      at PluginPass.VariableDeclaration (/app/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:81:9)
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=233&linesState=233)      at newFn (/app/node_modules/@babel/traverse/lib/visitors.js:159:21)
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=234&linesState=234)      at NodePath._call (/app/node_modules/@babel/traverse/lib/path/context.js:46:20)
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=235&linesState=235)      at NodePath.call (/app/node_modules/@babel/traverse/lib/path/context.js:36:17)
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=236&linesState=236)      at NodePath.visit (/app/node_modules/@babel/traverse/lib/path/context.js:84:31)
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=237&linesState=237)      at TraversalContext.visitQueue (/app/node_modules/@babel/traverse/lib/context.js:96:16)
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=238&linesState=238)      at TraversalContext.visitSingle (/app/node_modules/@babel/traverse/lib/context.js:72:19)
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=239&linesState=239)      at TraversalContext.visit (/app/node_modules/@babel/traverse/lib/context.js:121:19)
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=240&linesState=240)      at traverseNode (/app/node_modules/@babel/traverse/lib/traverse-node.js:18:17)

**Comment by ndelangen** [comment]
patch has been released by the babel team:
https://www.npmjs.com/package/@babel/plugin-transform-block-scoping

**Comment by rhenanteix** [comment]
react 
```

ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Users/rhenan/Projetos/firedev/Design-System-Firedev/.storybook/preview.js: Cannot set property 'kind' of undefined
```

**Comment by ndelangen** [comment]
same @rhenanteix seems there's another problem upstream, unless we can somehow track down what's going wrong on our side, but I can't find any.

**Comment by rhenanteix** [comment]
So, I don't know if this error would help you with something, I'm still having doubts, I already deleted the node modules and tried to run it again and it ends up stopping at this error, I don't know if I would need to change something or not in the package.json for example @ndelangen 


```



Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Users/rhenan/Projetos/firedev/Design-System-Firedev/.storybook/preview.js: Cannot set property 'kind' of undefined
    at transformBlockScopedVariable (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:122:41)
    at PluginPass.VariableDeclaration (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:81:9)
    at newFn (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/traverse/lib/visitors.js:159:21)
    at NodePath._call (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/traverse/lib/path/context.js:84:31)
    at TraversalContext.visitQueue (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitSingle (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/traverse/lib/context.js:72:19)
    at TraversalContext.visit (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/traverse/lib/context.js:121:19)
    at traverseNode (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitSingle (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/traverse/lib/context.js:72:19)
    at TraversalContext.visit (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/traverse/lib/context.js:121:19)
    at traverseNode (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at traverse (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/traverse/lib/index.js:50:34)
    at transformFile (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/core/lib/transformation/index.js:83:29)
    at transformFile.next (<anonymous>)
    at run (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/core/lib/transformation/index.js:24:12)
    at run.next (<anonymous>)
    at transform (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>)
    at step (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/gensync/index.js:261:32)
    at :6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (:6006/Users/rhenan/Projetos/firedev/Design-System-Firedev/node_modules/gensync/index.js:223:11)
    at ./.storybook/preview.js (Introduction.stories.mdx:231:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./.storybook/preview.js-generated-config-entry.js (Introduction.stories.mdx:231:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at __webpack_exec__ (generated-stories-entry.cjs:6:1)
    at generated-stories-entry.cjs:6:1
    at __webpack_require__.O (chunk loaded:25:1)
```

**Comment by pcr-bmiller** [comment]
I installed the previous stable version of @babel/plugin-transform-block-scoping and my react application is now building successfully again.
`npm i @babel/plugin-transform-block-scoping@7.20.5`

**Comment by ndelangen** [comment]
Since this issue isn't fixable by upgrading packages on our side, I'm closing this PR in favour of the less disruptive one here: https://github.com/storybookjs/storybook/pull/20386

**Comment by ndelangen** [comment]
Thanks for posting a work-around @pcr-miller

**Comment by rhenanteix** [comment]
> I installed the previous stable version of @babel/plugin-transform-block-scoping and my react application is now building successfully again. `npm i @babel/plugin-transform-block-scoping@7.20.5`

Wow, thanks...

**Pull request closed without merging**
