### PR TITLE
Vue3: reset app instance before rendering stories

### PR DESCRIPTION
**Pull request by yannbf**
Issue: #18222

## What I did

Here's a video for context on what the issue is and what the change was, plus the result:

https://streamable.com/ruz2nh

## How to test

```
yarn bootstrap --core
cd examples/vue-3-cli
yarn storybook
# Access IssueStory
```

If you want to make changes to the vue3 rendering layer of Storybook and experiment with it:

```
yarn build vue3 --watch
```

As you make changes, HMR will kick in and you should be good to go

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
Nice one @yannbf !! can you please fix storyshots to fix the build?

**Comment by yannbf** [comment]
> Nice one @yannbf !! can you please fix storyshots to fix the build?

done!

**Comment by yannbf** [comment]
BTW in Docs mode I'm not sure how this would work if the stories are rendered inline. They all share the same instance of the app, so it will get overriden after every story renders.. meaning the last story "wins":

image

The problem would not happen if the stories were not inline rendered:
image

**Comment by shilman** [comment]
@yannbf is that modern inline rendering or legacy?

**Comment by yannbf** [comment]
> @yannbf is that modern inline rendering or legacy?

Legacy. With modern it behaves like this:

image

Makes sense I guess, as currently the previous app is unmounted when rendering a following story

**Comment by ndelangen** [comment]
@yannbf is this PR still in progress?

**Comment by yannbf** [comment]
> @yannbf is this PR still in progress?
> 
> Keep in mind modern online rendering will be the only method of inline rendering in 7.0

This has to be reevaluated once I'm back

**Comment by ndelangen** [comment]
@yannbf I'm fairly confident, this has become un-mergable after the frameworks refactor, Is this something that's still on your radar to ever continue?

**Pull request closed without merging**
