### PR TITLE
Dependencies: Revert the replacement of pkg-dir and read-pkg-up by fd-package-json

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes N/A

## What I did

When building a sandbox locally in no-link mode, for some reason, yarn can't install the package `fd-package-json`. It doesn't appear in the node_modules. Even a `yarn why fd-package-json` returns nothing:

https://cloud.nx.app/runs/jjlIC4hbiD

Therefore, I am reverting the following PRs:

- https://github.com/storybookjs/storybook/pull/28270
- https://github.com/storybookjs/storybook/pull/28272

cc @43081j

## Reproduction

```bash
yarn task --task sandbox --template cra/default-js --no-link
```

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by 43081j** [comment]
I wouldn't revert, I would fix forward, as the gains in dependency tree complexity and speed are worthwhile

I'll have a look into it 👍

**Comment by valentinpalkovic** [comment]
@43081j 
Currently, it blocks our local development, and since we are wrapping up and are in the QA phase for 8.2, it is a kind of blocker where we don't have an exact time when it gets fixed. We can re-introduce the change at any time, as soon as it doesn't cause any issues anymore.

**Comment by 43081j** [comment]
I understand

I'm happy to have a look into it in the next hour or so but if you can't wait, feel free to temporarily revert

Will give it a go locally meanwhile and figure it out

**Comment by 43081j** [comment]
@valentinpalkovic do you know where we can see the yarn version it was using?

i wonder if its a difference in versions somewhere down the line

locally the same command works for me (no-link sandbox)

**Comment by valentinpalkovic** [comment]
I'll take another look tomorrow!

**Comment by valentinpalkovic** [comment]
Even after running `git clean -xdf` and pruning the npm/yarn cache, I am still experiencing this issue. :/ Can you tell me which Node.js version you are using?

**Comment by valentinpalkovic** [comment]
@43081j I will close this since I figured out that the issue isn't connected to `fd-package-json` at all. We had an issue with verdaccio and cached dependencies. Thank you for your investigations, though! Much appreciated :)

**Comment by 43081j** [comment]
all good, let me know if you need any help with what it turned out to be 👍 

would be curious if anything, to know what was causing it 😅

**Comment by valentinpalkovic** [comment]
@43081j https://github.com/storybookjs/storybook/pull/28361 seems to fix the issue.

**Pull request closed without merging**
