### PR TITLE
Addon API: Fix `useAddonState` - allow falsy values as state

### PR DESCRIPTION
**Pull request by ndelangen**
## What I did

I was working on an addon and discovered that when setting the state to a falsy value `null`, `0` or `undefined`, etc.. that the state would get messed up.

Sometimes it would even be a `Promise` instance!

I decided to finally write some proper unit tests and found some more buggy behavior, which prompted me to finally pull it together and fix things proper.

I also added a bunch of code comments, making this hard to understand code hopefully easier to maintain in the future.

I also added some documentation in the form of a jsdoc comment

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [x] unit tests
- [ ] integration tests
- [x] end-to-end tests

#### Manual testing

I don't think manual tests are required

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by kasperpeulen — APPROVED** [review]
LGTM!

**Comment by ndelangen** [comment]
@kasperpeulen Thanks for looking at it.

I'd love to look at this (specifically why it actually breaks at runtime) with you.. maybe next week or so.

**Comment by valentinpalkovic** [comment]
Repinging @ndelangen and @kasperpeulen. Do you think this should make it into 7.6? What does it need to merge this?

**Comment by ndelangen** [comment]
no, won't be merged into 7.x

**Pull request closed without merging**
