### PR TITLE
Fix: Make index failures result in build failures

### LINKED ISSUE #20044: Make index failures result in build failures
### Describe the bug

Storybook generates a "story index" on startup which generates the sidebar.

Currently, when a story fails to parse, it will be skipped. This is "unsafe" in that it can hide problems in your storybook. Instead, the story index should fail to generate and your Storybook should break.

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
resolves https://github.com/storybookjs/storybook/issues/20044

## What I did

I made the storyIndexer fail hard on missing Meta, this seemed the only caught exception in the storyIndexGenerator.

### CODE REVIEW

**Review by tmeasday — COMMENTED** [review]
I'm OK with this change but we'll need to add something to the `MIGRATION.md` about it.

**Comment by ndelangen** [comment]
@tmeasday then I need a bit more details in the issue to resolve, is there another try-catch somewhere?

**Comment by tmeasday** [comment]
I'm not really sure of the reproduction or mechanism of failure @ndelangen. Maybe @shilman can weigh in. Just my reading of that issue didn't sound like a simple "you left out a default export":

> Currently, when a story fails to parse, it will be skipped.

**Review by shilman — COMMENTED** [review]
@yannbf you raised this issue with me, but sounds like @ndelangen can't reproduce this. can you verify that the error-swallowing behavior is fixed in the latest beta?

**Comment by yannbf** [comment]
> @yannbf you raised this issue with me, but sounds like @ndelangen can't reproduce this. can you verify that the error-swallowing behavior is fixed in the latest beta?

I don't recall exactly what the scenario was, so I vote we get back to this if we stumble upon it.

While trying to reproduce it though, I noticed a weird error, which might not happen that often, but the UI state in Storybook is not great:

image

It happens if you have broken JS in your story file while Storybook is already running.

**Comment by ndelangen** [comment]
Let's make that an separate issue with a clear steps to reproduce?

**Comment by tmeasday** [comment]
Dealing with indexing failures on HMR might be something we need to address better.

**Comment by ndelangen** [comment]
I'm confused, is this PR good to merge or not? @tmeasday @shilman @yannbf ?

If besides this PR we need to do more to solve the issue, let's make that clear in the issue?

**Comment by tmeasday** [comment]
I'm happy to merge this but I wonder if we just want to take a minute to think more holistically about the various types of errors you can get during indexing:
  - Parsing errors
  - Wrong/missing things in the CSF file errors
  - Duplicate/invalid story errors (cf https://github.com/storybookjs/storybook/issues/19094)

And how we want to present those errors to the user:
  - Should they stop the SB from starting? If not, how should the error present to the user?
  - Should they crash the server during HMR? If not, how should the error present to the user?
 
My 2c would be that we should figure out how we want the above to behave in 7.0 (keeping scope limited) and then figure out how far away we are from that right now.

**Comment by yannbf** [comment]
I agree with Tom! Will be tagging this PR as do not merge for now

**Comment by vanessayuenn** [comment]
Superseded by https://github.com/storybookjs/storybook/issues/20663

**Pull request closed without merging**
