### PR TITLE
Tech: make the version range of `vite` also allow for `vite` `4`

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: support vite 4?

## What I did

I allowed vite in the version range, this fixes `yarn start`. (in our `contribution.md`)
It might also just be the right thing to do?

### CODE REVIEW

**Comment by IanVS** [comment]
It looks like this is an alternate solution to https://github.com/storybookjs/storybook/pull/20281?  Is there a reason not to go the route I took there?

**Comment by ndelangen** [comment]
NO there isn't. @JReinhold asked me to look into his svelte PR, and when I did I noticed the yarn failure, so I fixed it, and extracted the fix out into it's own PR here.

**Comment by ndelangen** [comment]
@IanVS I do not know what's going on with that PR, I'm happy to prefer that one over this one, for sure.
But I'd love to have `yarn start` and `vite` sandboxes in general work without linking, which is all I wanted to achieve in this PR.

**Comment by ndelangen** [comment]
I can't reproduce this unit-test fail locally. Argh I feel like giving up on this.

**Comment by IanVS** [comment]
I found the issue in the other PR(https://github.com/storybookjs/storybook/pull/20281). `react-docgen` wasn't being pinned correctly.

**Comment by ndelangen** [comment]
ok, I'll close it again

**Pull request closed without merging**
