### PR TITLE
CLI: Install latest storybook testing-library version in init

### PR DESCRIPTION
**Pull request by yannbf**
Closes https://github.com/storybookjs/testing-library/issues/39

**This PR is targeting main**

## What I did

This PR removes a version specifier when adding `@storybook/testing-library`, resolving the referenced issue

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Check that you did not get `@storybook/testing-library@0.0.14-next.2` as a dependency
3. Check that you did get `@storybook/testing-library@0.2.0` as a dependency

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by kasperpeulen** [comment]
@yannbf LGTM, but why are you not targetting next, with a `patch` label instead?

**Comment by yannbf** [comment]
> @yannbf LGTM, but why are you not targetting next, with a `patch` label instead?

Because in `next` we should use `@storybook/testing-library@^0.2.0-next.0` which points to @next versions of Storybook, whereas here it should point to @latest

**Review by kasperpeulen — APPROVED** [review]
LGTM!

**Comment by yannbf** [comment]
This PR is not needed anymore. Closing

**Pull request closed without merging**
