### PR TITLE
Tech: make tests use SWC, not babel

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: #18732

Telescoped on: https://github.com/storybookjs/storybook/pull/20156

And now using SWC for transforming in jest

### CODE REVIEW

**Review by tmeasday — COMMENTED** [review]
Wow, seems cool. So do we need to go back to using global vars for `it/expect` etc?

**Comment by ndelangen** [comment]
@tmeasday honestly, it's been a bit of an experimentation. Seeing how much babel stuff I could clean-up.

Good news is: It seems I can make all of it go away, pretty much!

---

Because of the long list of telescoped PRs (trying to make smaller PRs that can be reviewed) I easily get into merge conflicts, and then try to fix them any way I can.

I suppose we should chat about these PRs and if we want them in 7.0 at all. If we decide we DO, I should start running all sandboxes on them, and get them merged 1 by 1, slowly and carefully.

**Comment by IanVS** [comment]
Any reason this needs to be telescoped onto the other PRs, and we shouldn't just commit it straight to `next`?

**Comment by ndelangen** [comment]
That sounds like a plan @IanVS!

It's probably not going to get the highest priority from me, since i only have a few more days until my trip.

This sounds like an easy contribution for someone to pick as their first contribution maybe?

**Comment by ifndefdeadmau5** [comment]
May I take this one if anyone wouldn't mind? : )

**Comment by ndelangen** [comment]
closed in favor of https://github.com/storybookjs/storybook/pull/20397

**Pull request closed without merging**
